config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  root 'work_times#index'

  resources :users
  resources :projects
  resources :work_times
  resources :kinds
end

app/models/work_time.rb
# == Schema Information
#
# Table name: work_times
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  project_id :integer
#  form       :string(255)
#  action     :string(255)
#  date       :date
#  time       :decimal(10, )
#  comment    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  kind_id    :integer
#

class WorkTime < ActiveRecord::Base
  ### settings ###

  ### relations and scopes ###
  belongs_to :user
  belongs_to :project
  belongs_to :kind

  #### validations ###
  validates_presence_of :user, :project, :date, :time, :kind

  #### class methods ####
  def self.sum_time
    sum(:time)
  end

  #### object methods ###

end

app/controllers/work_times_controller.rb
class WorkTimesController < ApplicationController
  before_filter :set_arguments
  before_filter :set_work_time, only: [:edit, :destroy, :update]

  def index
    @work_time  = current_user.work_times.new
  end

  def create
    @work_time  = current_user.work_times.new(work_time_params)

    if @work_time.save
      redirect_to work_times_path, notice: t('save_work_time')
    else
      render :index
    end
  end

  def edit
  end

  def update
    if @work_time.update_attributes(work_time_params)
      flash[:success] = 'Zmiana przebiegła pomyślnie'
      redirect_to work_times_path
    else
      flash[:danger] = 'Podczas edycji występił błąd'
      redirect_to work_times_path
    end
  end

  def destroy
    if @work_time.destroy
      flash[:success] = 'Pomyślnie usunięto pozycję'
      redirect_to work_times_path
    else
      flash[:danger] = 'Wystąpił błąd podczas usuwania'
      render :index
    end
  end

  private

  def work_time_params
    params.require(:work_time).permit(:project_id, :kind_id, :time, :date, :comment)
  end

  def set_arguments
    @work_times = current_user.work_times.order('date DESC', 'id DESC')
  end

  def set_work_time
    @work_time = WorkTime.find(params[:id])
  end
end

app/helpers/work_times_helper.rb
module WorkTimesHelper

  #TODO refactor to decorator
  def progress_bar_class
    r = current_user.percentage_realization.to_f
    if r < 15
      "progress-bar-danger"
    elsif r >= 15 && r < 45
      "progress-bar-warning"
    elsif r >= 45 && r < 85
      "progress-bar-info"
    else
      "progress-bar-success"
    end
  end
end

app/views/work_times/_edit.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
      %h4#myModalLabel.modal-title Edytuj wpis
    .modal-body
      .row
        .col-md-12
          =simple_form_for @work_time, :html => { :class => 'form-horizontal' } do |f|
            =f.association  :project, collection: current_user.projects, input_html: { class: "select2"}, label: :project
            =f.association  :kind, input_html: { class: "select2"}, label: :kind
            =f.input        :time, label: :time
            =f.input        :date, as: :string, input_html: { class: "date", value: Date.today }, label: :date
            =f.input        :comment, label: :comment
            =f.button       :submit, class: 'btn btn-success'

app/views/work_times/edit.js.erb
$("#Modal").html("<%= j render "edit"%>");
$('#Modal').modal('show');
bind_inputs('#Modal');

app/views/work_times/index.html.haml
- provide :title, t('shared.work_times')
- prc = current_user.percentage_realization
.row
  .col-md-10.col-md-offset-1
    .progress
      -if current_user.limit?
        .progress-bar{style: "width: #{prc}", class: progress_bar_class}
          = prc
      -else
        .progress-bar.progress-bar-warning{style: 'width: 100%'}
          =link_to 'Ustaw swój limit(cel) miesięczny!', edit_user_path(current_user)
.row
  .col-md-12
    %table.table.table-striped.rcp
      %thead
        %tr.info
          =simple_form_for @work_time do |f|
            .form-inputs
              %td= f.input :date, as: :string,
                        input_html: { class: "date", value: f.object.date || Date.today }, label: false
              %td= f.association :project, collection: current_user.projects,
                        input_html: { class: "select2", placeholder: :project }, label: false
              %td= f.association :kind, input_html: { class: "select2", placeholder: :kind }, label: false
              %td= f.input :time, input_html: { placeholder: :time }, label: false
              %td= f.input :comment, input_html: { placeholder: :comment }, label: false
              %td.center= f.button :submit, '+', class: 'btn btn-success'
      %tbody
        -@work_times.each do |w|
          %tr
            %td= w.date
            %td
              %span
              = w.project
            %td
              %span.color{:style => "background-color:#{w.kind.color};"}
              = w.kind
            %td= w.time
            %td= w.comment
            %td
              = link_to_edit edit_work_time_path(w), remote: true
              = link_to_destroy work_time_path(w)
      %tfoot
        %th
        %th
        %th
        %th.center= @work_times.sum_time
        %th
        %th
        %th