config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  root 'work_times#index'

  resources :users
  resources :projects
  resources :work_times
  resources :kinds
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  short_name     :string(25)
#  state          :string(255)
#  closing_date   :date
#  ancestry       :string(255)
#  assigned_to_id :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  description    :text(65535)
#

class Project < ActiveRecord::Base
  ### settings ###
  has_ancestry
  self.per_page = 10

  ### relations and scopes ###
  belongs_to :assigned_to, class_name: 'User'
  has_and_belongs_to_many :users
  has_many :work_times
  has_many :kinds, through: :work_times

  scope :without_current, ->(current_id) {where('id <> ?', current_id || 0)}

  #### validations ###
  validates_presence_of   :name
  validates_presence_of   :short_name
  validates_uniqueness_of :short_name

  #### object methods ###
  def to_s
    self.short_name.humanize
  end

  def color
    name.pastel_color
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_filter :set_project, only: [:edit, :update, :destroy]


  def index
    @projects = Project.paginate(page: params[:page])
  end

  def new
    @project = Project.new
  end

  def create
    @project =  Project.new(project_params)
    if @project.save
      flash[:success] = 'Dodano projekt'
      redirect_to projects_path
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = 'Pomyślnie zmieniono projekt'
      redirect_to projects_url
    else
      flash[:danger] = 'Wystąpił błąd podczas zapisywania'
      render 'edit'
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = 'Projekt został usunięty.'
      redirect_to projects_path
    else
      flash[:danger] = 'Podczas usuwania występił błąd'
      redirect_to projects_path
    end
  end

  def project_params
    params.require(:project).permit(:short_name, :name, :assigned_to_id, :parent_id, user_ids: [])
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for @project do |f|
  .col-md-10.col-md-offset-1
    = f.error_notification
    .form-inputs
      .row
        .col-md-12
          =f.input :short_name
          =f.input :name
      .row
        .col-md-6
          =f.association :assigned_to, collection: collect_users , input_html: { class: "select2" }
          =f.input :parent_id, collection: collect_projects_parents(f.object.id), input_html: { class: "select2" },
            selected: f.object.parent_id, :include_blank => true
          =f.association :users, label_method: :full_name , input_html: { class: "select2" }
        .col-md-6
          =f.input :description
      .row
        .col-md-12
          %hr
          = f.button :submit, class: 'btn btn-success'
          = link_to t('cancel'), projects_path, class: 'btn btn-sm btn-default'

app/views/projects/edit.html.haml
- provide(:title, "Edytuj Projekt")
.row
  = render "form"

app/views/projects/index.html.haml
- provide(:title, 'Projekty')
.row
  .col-md-10.col-md-offset-1
    - if can? :create, Project
       #{link_to "+ dodaj projekt", new_project_path}
    %table.table.table-hover
      %thead
        %tr
          %th id
          %th nazwa skrócona
          %th nazwa
          %th status
          %th przypisany do
          %th projekt nadrzędny
          %th akcje
      %tbody
        - @projects.each do |p|
          %tr
            %th= p.id
            %th= p.short_name
            %td= p.name
            %td= p.state
            %td= p.assigned_to.andand.email
            %td= p.parent.andand.shortname
            %td
              = link_to_edit edit_project_path(p)
              = link_to_destroy project_path(p)
            %tr
              %td
              %th osoby w projekcie:
              %td{colspan: 5}
                -p.users.each do |u|
                  = u.complex_name
                  %br
    = will_paginate @projects

app/views/projects/new.html.haml
- provide(:title, "Dodaj Projekt")
.row
  = render "form"