config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  root 'work_times#index'

  resources :users
  resources :projects
  resources :work_times
  resources :kinds
end

app/views/layouts/_actions_menu.html.haml
.actions
  .row
    .col-md-3.col-xs-12
      %h2= yield(:title)
    .col-md-9.col-xs-12
      %ul.nav.nav-pills.nav-justified.navbar-right.navbar-navigation
        %li= nav_link(t('shared.work_times'), work_times_path)
        %li= nav_link(t('shared.projects'), projects_path)
        %li= nav_link(t('shared.kinds'), kinds_path)
        %li= nav_link(t('shared.users'), users_path) if current_user.admin?

app/views/layouts/_body_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse{:role => ""}
    .navbar-inner
      .container
        %row
          .col-md-3
            = link_to "MAP", '/', class: "navbar-brand"
          .col-md-9
            - if signed_in?
              %nav
                %ul.nav.navbar-nav.navbar-right.navbar-top
                  %li.dropdown
                    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                      = current_user.email
                      %b.caret
                    %ul.dropdown-menu{"aria-labelledby" => "dLabel", :role => "menu"}
                      - if current_user.admin?
                        %li= link_to "profil", current_user
                      %li= link_to "ustawienia", edit_user_path(current_user)
                      %li.divider{:role => "presentation"}
                      %li= link_to "wyloguj", destroy_user_session_path, method: :delete

app/views/layouts/_modal.html.haml
#Modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4#myModalLabel.modal-title Modal title
      .modal-body
        Chyba coś poszło nie tak...

app/views/layouts/_select_form.html.haml
.row
  .col-md-12
    = simple_form_for 'work_time', :html => { :class => 'form-inline' } do |f|
      %table
        %tr
          %td= f.input :centrum_id, :collection => @centrum.collect{ |c| [c.symbol, c.id]}, :selected => session[:centrum_id], label_html: { size: 'auto', class: 'sr-only'}, input_html: { class: 'input-sm', placeholder: 'centrum'}
          %td= f.input :project, :collection =>@project.collect{ |p| [p.akronim, p.project_id]}, :include_blank => 'Wybierz projekt', :selected => session[:project_id] , label_html: { class: 'sr-only'}, input_html: { size: 'auto', class: 'input-sm', placeholder: 'projekt'}
          %td= f.input :sub_project, :collection=>@sub_project.collect{ |s| [s.akronim, s.id]} , :include_blank => '', :selected => session[:sub_project_id], label_html: { class: 'sr-only'}, input_html: { size: 'auto', class: 'input-sm', placeholder: 'sub projekt'}, required: false
          - if controller_name == 'customers'
            %td= f.input :customer_id, :collection=> @customer.collect{ |cus| [cus.akronim, cus.customer_id]}, :include_blank => 'Wybierz klienta', :selected => session[:customer_id], label_html: { class: 'sr-only'}, input_html: { size: 'auto', class: 'input-sm', placeholder: 'klient'}, required: true
          - elsif controller_name == 'projects' || 'plans' || 'realizations'
            %td= f.input :customer_id, :collection=> @customer ? [[@customer.akronim, @customer.id]] : [], :selected => session[:customer_id], label_html: { class: 'sr-only'}, input_html: { size: 'auto', class: 'input-sm', readonly: 'readonly', placeholder: 'klient'}, required: false, readonly: 'true'
            :javascript
              $('#work_time_customer_id').prop('readonly', true);
          %td= f.button :submit, 'Pokaż', class: 'btn btn-sm btn-default'
%hr/

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      MAP | #{yield(:title)}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/body_header'
    .container
      #main
        #box
          / tymczasowo do utworzenia formularza logowania
          - if signed_in?
            = render 'layouts/actions_menu'
          = yield
      = debug(params) if Rails.env.development?
    = render :partial => '/layouts/modal'

    = gflash :position => :bottom_left